# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: ["src"]
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.14.3
    hooks:
    -   id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: .*/tests/.*
- repo: https://github.com/kynan/nbstripout
  rev: 0.3.9
  hooks:
    - id: nbstripout
      args:
        - --extra-keys
        - "metadata.kernelspec cell.metadata.executionInfo"
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=5120"]
    -   id: end-of-file-fixer
        exclude: '\.Rd'
    -   id: trailing-whitespace
{% if cookiecutter.add_r_precommit_hooks == "Yes" %}
# R specific hooks: https://github.com/lorenzwalthert/precommit
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.2
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: roxygenize
    # codemeta must be above use-tidy-description when both are used
    # -   id: codemeta-description-updated
    -   id: use-tidy-description
    -   id: lintr
        exclude: renv/activate.R
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
{% endif -%}
